# Generated by Django 3.2 on 2023-10-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_company_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_id',
            new_name='id',
        ),
    ]
